export{default as NavBar} from './Components/NavBar';
export {default as Feed} from './Components/Feed';
export {default as ChannelDetail} from './Components/ChannelDetail';
export {default as VideoDetial} from './Components/VideoDetial';
export {default as SearchFeed} from './Components/SearchFeed';
export {default as SearchBar} from './Components/SearchBar';
export {default as SideBar} from './Components/SideBar';
export {default as Videos} from './Components/Videos';
export {default as VideoCard} from './Components/VideoCard';
export {default as ChannelCard} from './Components/ChannelCard';
export {default as Loader} from './Components/Loader';